export const colorVariants = {
  solid: {
    default: "bg-default text-default-foreground",
    primary: "bg-primary text-primary-foreground",
    secondary: "bg-secondary text-secondary-foreground", 
    success: "bg-success text-success-foreground",
    warning: "bg-warning text-warning-foreground",
    danger: "bg-danger text-danger-foreground",
  },
  bordered: {
    default: "border-default text-foreground",
    primary: "border-primary text-primary",
    secondary: "border-secondary text-secondary",
    success: "border-success text-success", 
    warning: "border-warning text-warning",
    danger: "border-danger text-danger",
  },
  light: {
    default: "text-default",
    primary: "text-primary",
    secondary: "text-secondary",
    success: "text-success",
    warning: "text-warning", 
    danger: "text-danger",
  },
  flat: {
    default: "bg-default/20 text-default-700",
    primary: "bg-primary/20 text-primary-700",
    secondary: "bg-secondary/20 text-secondary-700",
    success: "bg-success/20 text-success-700",
    warning: "bg-warning/20 text-warning-700",
    danger: "bg-danger/20 text-danger-700",
  },
  faded: {
    default: "border-default bg-default-100 text-default-foreground",
    primary: "border-default bg-default-100 text-primary",
    secondary: "border-default bg-default-100 text-secondary",
    success: "border-default bg-default-100 text-success",
    warning: "border-default bg-default-100 text-warning",
    danger: "border-default bg-default-100 text-danger",
  },
  shadow: {
    default: "shadow-lg shadow-default/50 bg-default text-default-foreground",
    primary: "shadow-lg shadow-primary/40 bg-primary text-primary-foreground",
    secondary: "shadow-lg shadow-secondary/40 bg-secondary text-secondary-foreground",
    success: "shadow-lg shadow-success/40 bg-success text-success-foreground",
    warning: "shadow-lg shadow-warning/40 bg-warning text-warning-foreground",
    danger: "shadow-lg shadow-danger/40 bg-danger text-danger-foreground",
  },
  ghost: {
    default: "border-default text-default hover:!bg-default",
    primary: "border-primary text-primary hover:!bg-primary hover:!text-primary-foreground",
    secondary: "border-secondary text-secondary hover:!bg-secondary hover:!text-secondary-foreground",
    success: "border-success text-success hover:!bg-success hover:!text-success-foreground",
    warning: "border-warning text-warning hover:!bg-warning hover:!text-warning-foreground",
    danger: "border-danger text-danger hover:!bg-danger hover:!text-danger-foreground",
  },
};
